import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import { Analytics } from "@vercel/analytics/react"

import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import "@uploadthing/react/styles.css"
import { ourFileRouter } from "@/app/api/uploadthing/core";

import TanstackProvider from "@/providers/TanstackProvider";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "ClipsFast",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
  
  return (
    <html lang="en">
      <body className={inter.className} >
        <Analytics />
        <NextSSRPlugin
          routerConfig={extractRouterConfig(ourFileRouter)}
        />
        <TanstackProvider>
          {children}
          
        </TanstackProvider>
      </body>
    </html>
  );
}
