import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";

import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import "@uploadthing/react/styles.css"
import { ourFileRouter } from "@/app/api/uploadthing/core";

import TanstackProvider from "@/providers/TanstackProvider";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "ClipsFast",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
  function Navbar() {
    return (
      <nav className="flex justify-left h-16 items-center px-12">
        <div className="">
          <Image
            src={"assets/waitlist/logo.svg"}
            alt="logo"
            width={130}
            height={60}
          />
        </div>
      </nav>
    )
  }
  
  return (
    <html lang="en">
      <body className={inter.className} style={{background:"#FFF5E1"}}>
        <NextSSRPlugin
          routerConfig={extractRouterConfig(ourFileRouter)}
        />
        <TanstackProvider>
          <Navbar />
          {children}
          
          <div className="bg-[#0C1844] w-full text-white p-16">
            @j4ckyhnc
          </div>
        </TanstackProvider>
      </body>
    </html>
  );
}
